blank_issues_enabled: true

contact_links:
  - name: Beta feedback & discussion
    url: https://github.com/Thinkr1/Loffty/discussions
    about: Share your experience, ideas, questions, and general feedback with the Loffty community by starting a discussion.

  - name: Latest release
    url: https://github.com/Thinkr1/Loffty/releases/latest
    about: Download the latest version of Loffty.

  - name: Loffty documentation
    url: https://github.com/Thinkr1/Loffty#readme
    about: Read the README for info.
